### ISSUE TITLE
Check input validity

### ISSUE THREAD

**Issue by MoeMorox** [mixerp/MixERP.Net.VCards#2]
Hi there,

thanks for your great lib first!

I'm parsing uploaded files as vCards so that I can import them in my DB.
This works pretty nice, almost a little bit too nice:
If the input in "MixERP.Net.VCards.Deserializer.GetVCards()" is **not** a valid vCard, I (sometimes) also get back an empty vCard.
I Tried this with the following "vCard":
```
OUGEGlnvdog
rwz
53zu
hh4
5ehtde
§%
4
6&
```
Is there some validation method to use I overlooked?
Thanks in advance!

**Comment by mixerp** [comment]
LOL, you got me. This library is too forgiving because there are hundreds of various wrong vCard implementations, forcing us to be as nice as possible. Maybe we could validate if the input contains "begin vcard" and "end vcard".

**Comment by MoeMorox** [comment]
Added a Regex to check it, asking for "feedback".
Also, is there any reason you don't throw exceptions? Would be easier to handle than just returning an empty VCard?

**Comment by mixerp** [comment]
We designed this library for our AddressBook app. We avoid throwing exceptions so that we're able to parse malformed vCards as well. The point is to enable the consumer to decide whether or not they want to throw exception. For example, we throw exceptions at the application end, not the library itself:

https://github.com/frapid/frapid/blob/master/src/Frapid.Web/Areas/Frapid.AddressBook/Models/VCardImporter.cs


## Feedback
I think it's the right thing to do by checking if the input is actually a vCard file. So, we could throw parse exception here:

https://github.com/MoeMorox/MixERP.Net.VCards/blob/487c9427a8893ab6865b01bae96a56c2b770af64/src/MixERP.Net.VCards/Deserializer.cs#L15-L18

```
if (string.IsNullOrWhiteSpace(contents) || !contents.TrimStart().StartsWith("BEGIN:VCARD") || !contents.TrimEnd().EndsWith("END:VCARD"))
{
    throw new VCardParseException("The input is not a valid vCard file.");
}
```

## VCardParseException
```
using System;
using System.Runtime.Serialization;

namespace MixERP.Net.VCards
{
    [Serializable]
    public sealed class VCardParseException : Exception
    {
        public VCardParseException()
        {
        }

        public VCardParseException(string message) : base(message)
        {
        }

        public VCardParseException(string message, Exception innerException) : base(message, innerException)
        {
        }

        public VCardParseException(SerializationInfo info, StreamingContext context) : base(info, context)
        {
        }
    }
}
```

What do you think?

**Comment by MoeMorox** [comment]
Sounds perfect to me, I'll update the PR tomorrow.
Thanks for your time!

**Comment by MoeMorox** [comment]
Is Serialization for the exception important?
I excperienced some issues with System.Runtime.Serialization and netstandard*, you'd need [System.Runtime.Serialization.Primitives](https://www.nuget.org/packages/System.Runtime.Serialization.Primitives/) here.
I'm using VS2017 with the new .csproj file and thus can't test this with this repository in mind.
[This](http://stackoverflow.com/a/34195433) seems to be the right solution, unfortunately not for VS17.

Thanks in advance for your help!

**Comment by mixerp** [comment]
IMHO, you can omit the Serialize attribute because things have changed substantially in Core.

**Comment by MoeMorox** [comment]
Yeah Core  is a bit.. weird.
PR should now include everything.(?)

**Comment by MoeMorox** [comment]
Thanks!
